### ISSUE TITLE
Espoo is currently failing with error

### ISSUE THREAD

**Issue by Grenguar** [Grenguar/fuel-api-finland-serverless#2]
2020-10-04 13:45:06.412 (+03:00)        a4410309-9757-4b8f-badb-9831be0b6bbd    ERROR   Invoke Error    {"errorType":"TypeError","errorMessage":"Cannot read property 'next' of undefined","stack":["TypeError: Cannot read property 'next' of undefined","    at FuelScraper.parseStationRow (/var/task/src/fuelScraper.js:61:36)","    at Node.<anonymous> (/var/task/src/fuelScraper.js:46:38)","    at initialize.exports.each (/var/task/node_modules/cheerio/lib/api/traversing.js:300:24)","    at FuelScraper.<anonymous> (/var/task/src/fuelScraper.js:45:26)","    at Generator.next (<anonymous>)","    at fulfilled (/var/task/src/fuelScraper.js:5:58)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]}

**Comment by Grenguar** [comment]
Tampere also is failing
